name: 'Mark all PRs as stale'
on:
  pull_request:
    types: [opened]
  schedule:
    - cron: '28 6 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-pr-message: 'Please note that Pull Requests are neither merged nor reviewed! Your Pull Requests only trigger continuous integration builds and tests in this repository and will automatically be closed after a month. As soon as you are happy with the result, please send the patches to the mailing list at devel@rtems.org. See https://lists.rtems.org for instructions how to register for that list. Thank you. '
          days-before-stale: -1
          days-before-close: -1
          days-before-pr-stale: 0
          days-before-pr-close: 30
